-- MySQL Script generated by MySQL Workbench
-- Mon Nov  2 15:20:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema notariadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema notariadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notariadb` DEFAULT CHARACTER SET utf8 ;
USE `notariadb` ;

-- -----------------------------------------------------
-- Table `notariadb`.`doctypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notariadb`.`doctypes` (
  `doctype_id` INT NOT NULL,
  `description` VARCHAR(50) NULL,
  PRIMARY KEY (`doctype_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notariadb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notariadb`.`usuarios` (
  `id` VARCHAR(15) NOT NULL,
  `doctype_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `surname` VARCHAR(50) NOT NULL,
  `expedition_place` VARCHAR(100) NULL,
  `expedition_date` DATE NULL,
  `birth_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_doctypes_usuarios_idx` (`doctype_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_doctype_id`
    FOREIGN KEY (`doctype_id`)
    REFERENCES `notariadb`.`doctypes` (`doctype_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notariadb`.`places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notariadb`.`places` (
  `place_id` INT NOT NULL,
  `department` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`place_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notariadb`.`notarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notariadb`.`notarios` (
  `id` VARCHAR(15) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `surname` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notariadb`.`bloodtypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notariadb`.`bloodtypes` (
  `bloodtype_id` INT NOT NULL,
  `name` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`bloodtype_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notariadb`.`nac_attaches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notariadb`.`nac_attaches` (
  `attach_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`attach_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notariadb`.`nacimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notariadb`.`nacimientos` (
  `nuip` VARCHAR(15) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `surname1` VARCHAR(50) NOT NULL,
  `surname2` VARCHAR(50) NOT NULL,
  `sex` CHAR(1) NOT NULL,
  `place_id` INT NOT NULL,
  `bloodtype_id` INT NOT NULL,
  `birth_date` DATETIME NOT NULL,
  `reg_date` DATETIME NOT NULL,
  `mom_id` VARCHAR(15) NOT NULL,
  `dad_id` VARCHAR(15) NOT NULL,
  `witness1_id` VARCHAR(15) NOT NULL,
  `witness2_id` VARCHAR(15) NULL,
  `relateduser_id` VARCHAR(15) NULL,
  `notary_id` VARCHAR(15) NOT NULL,
  `attach_id` INT NOT NULL,
  `attach_description` VARCHAR(75) NOT NULL,
  `fileroute` VARCHAR(500) NULL,
  PRIMARY KEY (`nuip`, `name`),
  INDEX `fk_nacimientos_places_id_idx` (`place_id` ASC) VISIBLE,
  INDEX `fk_nacimientos_mom_id_idx` (`mom_id` ASC) VISIBLE,
  INDEX `fk_nacimientos_dad_id_idx` (`dad_id` ASC) VISIBLE,
  INDEX `fk_nacimientos_witness1_id_idx` (`witness1_id` ASC) VISIBLE,
  INDEX `fk_nacimientos_witness2_id_idx` (`witness2_id` ASC) VISIBLE,
  INDEX `fk_nacimientos_relateduser_id_idx` (`relateduser_id` ASC) VISIBLE,
  INDEX `fk_nacimientos_notary_id_idx` (`notary_id` ASC) VISIBLE,
  INDEX `fk_nacimientos_bloodtype_id_idx` (`bloodtype_id` ASC) VISIBLE,
  INDEX `fk_nacimientos_attach_id_idx` (`attach_id` ASC) VISIBLE,
  CONSTRAINT `fk_nacimientos_places_id`
    FOREIGN KEY (`place_id`)
    REFERENCES `notariadb`.`places` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nacimientos_mom_id`
    FOREIGN KEY (`mom_id`)
    REFERENCES `notariadb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nacimientos_dad_id`
    FOREIGN KEY (`dad_id`)
    REFERENCES `notariadb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nacimientos_witness1_id`
    FOREIGN KEY (`witness1_id`)
    REFERENCES `notariadb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nacimientos_witness2_id`
    FOREIGN KEY (`witness2_id`)
    REFERENCES `notariadb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nacimientos_relateduser_id`
    FOREIGN KEY (`relateduser_id`)
    REFERENCES `notariadb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nacimientos_notary_id`
    FOREIGN KEY (`notary_id`)
    REFERENCES `notariadb`.`notarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nacimientos_bloodtype_id`
    FOREIGN KEY (`bloodtype_id`)
    REFERENCES `notariadb`.`bloodtypes` (`bloodtype_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nacimientos_attach_id`
    FOREIGN KEY (`attach_id`)
    REFERENCES `notariadb`.`nac_attaches` (`attach_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notariadb`.`mat_attaches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notariadb`.`mat_attaches` (
  `attach_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`attach_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notariadb`.`matrimonios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notariadb`.`matrimonios` (
  `id` VARCHAR(15) NOT NULL,
  `name1` VARCHAR(50) NOT NULL,
  `surname1` VARCHAR(50) NOT NULL,
  `relateduser1_id` VARCHAR(15) NULL,
  `name2` VARCHAR(45) NOT NULL,
  `surname2` VARCHAR(50) NOT NULL,
  `relateduser2_id` VARCHAR(45) NULL,
  `place_id` INT NOT NULL,
  `weeding_date` DATE NOT NULL,
  `reg_date` DATE NOT NULL,
  `witness1_id` VARCHAR(15) NOT NULL,
  `notary_id` VARCHAR(15) NOT NULL,
  `attach_id` INT NOT NULL,
  `attach_description` VARCHAR(75) NOT NULL,
  `fileroute` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nacimientos_places_id_idx` (`place_id` ASC) VISIBLE,
  INDEX `fk_nacimientos_witness1_id_idx` (`witness1_id` ASC) VISIBLE,
  INDEX `fk_nacimientos_relateduser_id_idx` (`relateduser1_id` ASC) VISIBLE,
  INDEX `fk_matrimonios_relateduser2_id_idx` (`relateduser2_id` ASC) VISIBLE,
  INDEX `fk_matrimonios_notary_id_idx` (`notary_id` ASC) VISIBLE,
  INDEX `fk_matrimonios_attach_id_idx` (`attach_id` ASC) VISIBLE,
  CONSTRAINT `fk_matrimonios_places_id`
    FOREIGN KEY (`place_id`)
    REFERENCES `notariadb`.`places` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matrimonios_witness1_id`
    FOREIGN KEY (`witness1_id`)
    REFERENCES `notariadb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matrimonios_relateduser1_id`
    FOREIGN KEY (`relateduser1_id`)
    REFERENCES `notariadb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matrimonios_relateduser2_id`
    FOREIGN KEY (`relateduser2_id`)
    REFERENCES `notariadb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matrimonios_notary_id`
    FOREIGN KEY (`notary_id`)
    REFERENCES `notariadb`.`notarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matrimonios_attach_id`
    FOREIGN KEY (`attach_id`)
    REFERENCES `notariadb`.`mat_attaches` (`attach_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notariadb`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notariadb`.`medicos` (
  `id` VARCHAR(15) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `surname` VARCHAR(50) NOT NULL,
  `medic_card` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notariadb`.`def_attaches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notariadb`.`def_attaches` (
  `attach_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`attach_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notariadb`.`defunciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notariadb`.`defunciones` (
  `id` VARCHAR(15) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `surname` VARCHAR(50) NOT NULL,
  `relateduser_id` VARCHAR(15) NULL,
  `medic_id` VARCHAR(15) NOT NULL,
  `place_id` INT NOT NULL,
  `dead_date` DATE NOT NULL,
  `reg_date` DATE NOT NULL,
  `witness1_id` VARCHAR(15) NOT NULL,
  `notary_id` VARCHAR(15) NOT NULL,
  `attach_id` INT NOT NULL,
  `attach_description` VARCHAR(75) NOT NULL,
  `fileroute` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nacimientos_places_id_idx` (`place_id` ASC) VISIBLE,
  INDEX `fk_nacimientos_witness1_id_idx` (`witness1_id` ASC) VISIBLE,
  INDEX `fk_nacimientos_relateduser_id_idx` (`relateduser_id` ASC) VISIBLE,
  INDEX `fk_defunciones_medic_id_idx` (`medic_id` ASC) VISIBLE,
  INDEX `fk_defunciones_notary_id_idx` (`notary_id` ASC) VISIBLE,
  INDEX `fk_defunciones_attach_id_idx` (`attach_id` ASC) VISIBLE,
  CONSTRAINT `fk_defunciones_places_id`
    FOREIGN KEY (`place_id`)
    REFERENCES `notariadb`.`places` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_defunciones_witness1_id`
    FOREIGN KEY (`witness1_id`)
    REFERENCES `notariadb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_defunciones_relateduser1_id`
    FOREIGN KEY (`relateduser_id`)
    REFERENCES `notariadb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_defunciones_notary_id`
    FOREIGN KEY (`notary_id`)
    REFERENCES `notariadb`.`notarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_defunciones_medic_id`
    FOREIGN KEY (`medic_id`)
    REFERENCES `notariadb`.`medicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_defunciones_attach_id`
    FOREIGN KEY (`attach_id`)
    REFERENCES `notariadb`.`def_attaches` (`attach_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `notariadb`.`bloodtypes`
-- -----------------------------------------------------
START TRANSACTION;
USE `notariadb`;
INSERT INTO `notariadb`.`bloodtypes` (`bloodtype_id`, `name`) VALUES (1, 'A+');
INSERT INTO `notariadb`.`bloodtypes` (`bloodtype_id`, `name`) VALUES (2, 'A-');
INSERT INTO `notariadb`.`bloodtypes` (`bloodtype_id`, `name`) VALUES (3, 'B+');
INSERT INTO `notariadb`.`bloodtypes` (`bloodtype_id`, `name`) VALUES (4, 'B-');
INSERT INTO `notariadb`.`bloodtypes` (`bloodtype_id`, `name`) VALUES (5, 'O+');
INSERT INTO `notariadb`.`bloodtypes` (`bloodtype_id`, `name`) VALUES (6, 'O-');
INSERT INTO `notariadb`.`bloodtypes` (`bloodtype_id`, `name`) VALUES (7, 'AB+');
INSERT INTO `notariadb`.`bloodtypes` (`bloodtype_id`, `name`) VALUES (8, 'AB-');

COMMIT;

