using NotariaDB.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace NotariaDB.Seeders
{
    class CitiesSeeder : ISeeder<Cities>
    {
        public Cities[] Run()
        {
            Cities[] seeds =
            {
                new Cities { Id = 201, Name = "PUERTO NARIÑO"},
                new Cities { Id = 202, Name = "LETICIA"},
                new Cities { Id = 203, Name = "MEDELLÍN"},
                new Cities { Id = 204, Name = "ABEJORRAL"},
                new Cities { Id = 205, Name = "ABRIAQUI"},
                new Cities { Id = 206, Name = "ALEJANDRÍA"},
                new Cities { Id = 207, Name = "AMAGÁ"},
                new Cities { Id = 208, Name = "AMALFI"},
                new Cities { Id = 209, Name = "ANDES"},
                new Cities { Id = 210, Name = "ANGELÓPOLIS"},
                new Cities { Id = 211, Name = "ANGOSTURA"},
                new Cities { Id = 212, Name = "ANORÍ"},
                new Cities { Id = 213, Name = "ANTIOQUIA"},
                new Cities { Id = 214, Name = "ANZÁ"},
                new Cities { Id = 215, Name = "APARTADÓ"},
                new Cities { Id = 216, Name = "ARBOLETES"},
                new Cities { Id = 217, Name = "ARGELIA"},
                new Cities { Id = 218, Name = "ARMENIA"},
                new Cities { Id = 219, Name = "BARBOSA"},
                new Cities { Id = 220, Name = "BELMIRA"},
                new Cities { Id = 221, Name = "BELLO"},
                new Cities { Id = 222, Name = "BETANIA"},
                new Cities { Id = 223, Name = "BETULIA"},
                new Cities { Id = 224, Name = "BOLÍVAR"},
                new Cities { Id = 225, Name = "BRISEÑO"},
                new Cities { Id = 226, Name = "BURITICÁ"},
                new Cities { Id = 227, Name = "CÁCERES"},
                new Cities { Id = 228, Name = "CAICEDO"},
                new Cities { Id = 229, Name = "CALDAS"},
                new Cities { Id = 230, Name = "CAMPAMENTO"},
                new Cities { Id = 231, Name = "CAÑASGORDAS"},
                new Cities { Id = 232, Name = "CARACOLÍ"},
                new Cities { Id = 233, Name = "CARAMANTA"},
                new Cities { Id = 234, Name = "CAREPA"},
                new Cities { Id = 235, Name = "CARMEN DE VIBORAL"},
                new Cities { Id = 236, Name = "CAROLINA"},
                new Cities { Id = 237, Name = "CAUCASIA"},
                new Cities { Id = 238, Name = "CHIGORODÓ"},
                new Cities { Id = 239, Name = "CISNEROS"},
                new Cities { Id = 240, Name = "COCORNÁ"},
                new Cities { Id = 241, Name = "CONCEPCIÓN"},
                new Cities { Id = 242, Name = "CONCORDIA"},
                new Cities { Id = 243, Name = "COPACABANA"},
                new Cities { Id = 244, Name = "DABEIBA"},
                new Cities { Id = 245, Name = "DON MATÍAS"},
                new Cities { Id = 246, Name = "EBÉJICO"},
                new Cities { Id = 247, Name = "EL BAGRE"},
                new Cities { Id = 248, Name = "ENTRERRÍOS"},
                new Cities { Id = 249, Name = "ENVIGADO"},
                new Cities { Id = 250, Name = "FREDONIA"},
                new Cities { Id = 251, Name = "FRONTINO"},
                new Cities { Id = 252, Name = "GIRALDO"},
                new Cities { Id = 253, Name = "GIRARDOTA"},
                new Cities { Id = 254, Name = "GÓMEZ PLATA"},
                new Cities { Id = 255, Name = "GRANADA"},
                new Cities { Id = 256, Name = "GUADALUPE"},
                new Cities { Id = 257, Name = "GUARNE"},
                new Cities { Id = 258, Name = "GUATAPÉ"},
                new Cities { Id = 259, Name = "HELICONIA"},
                new Cities { Id = 260, Name = "HISPANIA"},
                new Cities { Id = 261, Name = "ITAGÜÍ"},
                new Cities { Id = 262, Name = "ITUANGO"},
                new Cities { Id = 263, Name = "JARDÍN"},
                new Cities { Id = 264, Name = "JERICÓ"},
                new Cities { Id = 265, Name = "LA CEJA"},
                new Cities { Id = 266, Name = "LA ESTRELLA"},
                new Cities { Id = 267, Name = "LA PINTADA"},
                new Cities { Id = 268, Name = "LA UNIÓN"},
                new Cities { Id = 269, Name = "LIBORINA"},
                new Cities { Id = 270, Name = "MACEO"},
                new Cities { Id = 271, Name = "MARINILLA"},
                new Cities { Id = 272, Name = "MONTEBELLO"},
                new Cities { Id = 273, Name = "MURINDÓ"},
                new Cities { Id = 274, Name = "MUTATÁ"},
                new Cities { Id = 275, Name = "NARIÑO"},
                new Cities { Id = 276, Name = "NECOCLÍ"},
                new Cities { Id = 277, Name = "NECHÍ"},
                new Cities { Id = 278, Name = "OLAYA"},
                new Cities { Id = 279, Name = "PEÑOL"},
                new Cities { Id = 280, Name = "PEQUE"},
                new Cities { Id = 281, Name = "PUEBLORRICO"},
                new Cities { Id = 282, Name = "PUERTO BERRÍO"},
                new Cities { Id = 283, Name = "PUERTO NARE"},
                new Cities { Id = 284, Name = "PUERTO TRIUNFO"},
                new Cities { Id = 285, Name = "REMEDIOS"},
                new Cities { Id = 286, Name = "RETIRO"},
                new Cities { Id = 287, Name = "RIONEGRO"},
                new Cities { Id = 288, Name = "SABANALARGA"},
                new Cities { Id = 289, Name = "SABANETA"},
                new Cities { Id = 290, Name = "SALGAR"},
                new Cities { Id = 291, Name = "SAN ANDRÉS"},
                new Cities { Id = 292, Name = "SAN CARLOS"},
                new Cities { Id = 293, Name = "SAN FRANCISCO"},
                new Cities { Id = 294, Name = "SAN JERÓNIMO"},
                new Cities { Id = 295, Name = "SAN JOSÉ DE MONTAÑA"},
                new Cities { Id = 296, Name = "SAN JUAN DE URABÁ"},
                new Cities { Id = 297, Name = "SAN LUIS"},
                new Cities { Id = 298, Name = "SAN PEDRO"},
                new Cities { Id = 299, Name = "SAN PEDRO DE URABÁ"},
                new Cities { Id = 300, Name = "SAN RAFAEL"},
                new Cities { Id = 301, Name = "SAN ROQUE"},
                new Cities { Id = 302, Name = "SAN VICENTE"},
                new Cities { Id = 303, Name = "SANTA BÁRBARA"},
                new Cities { Id = 304, Name = "SANTA ROSA DE OSOS"},
                new Cities { Id = 305, Name = "SANTO DOMINGO"},
                new Cities { Id = 306, Name = "SANTUARIO"},
                new Cities { Id = 307, Name = "SEGOVIA"},
                new Cities { Id = 308, Name = "SONSÓN"},
                new Cities { Id = 309, Name = "SOPETRÁN"},
                new Cities { Id = 310, Name = "TÁMESIS"},
                new Cities { Id = 311, Name = "TARAZÁ"},
                new Cities { Id = 312, Name = "TARSO"},
                new Cities { Id = 313, Name = "TITIRIBÍ"},
                new Cities { Id = 314, Name = "TOLEDO"},
                new Cities { Id = 315, Name = "TURBO"},
                new Cities { Id = 316, Name = "URAMITA"},
                new Cities { Id = 317, Name = "URRAO"},
                new Cities { Id = 318, Name = "VALDIVIA"},
                new Cities { Id = 319, Name = "VALPARAÍSO"},
                new Cities { Id = 320, Name = "VEGACHÍ"},
                new Cities { Id = 321, Name = "VENECIA"},
                new Cities { Id = 322, Name = "VIGÍA DEL FUERTE"},
                new Cities { Id = 323, Name = "YALÍ"},
                new Cities { Id = 324, Name = "YARUMAL"},
                new Cities { Id = 325, Name = "YOLOMBÓ"},
                new Cities { Id = 326, Name = "YONDÓ (CASABE)"},
                new Cities { Id = 327, Name = "ZARAGOZA"},
                new Cities { Id = 328, Name = "ARAUCA"},
                new Cities { Id = 329, Name = "ARAUQUITA"},
                new Cities { Id = 330, Name = "CRAVO NORTE"},
                new Cities { Id = 331, Name = "FORTUL"},
                new Cities { Id = 332, Name = "PUERTO RONDÓN"},
                new Cities { Id = 333, Name = "FORTUL"},
                new Cities { Id = 334, Name = "PUERTO RONDÓN"},
                new Cities { Id = 335, Name = "SARAVENA"},
                new Cities { Id = 336, Name = "TAME"},
                new Cities { Id = 337, Name = "BARRANQUILLA"},
                new Cities { Id = 338, Name = "BARANOA"},
                new Cities { Id = 339, Name = "CAMPO DE LA CRUZ"},
                new Cities { Id = 340, Name = "CANDELARIA"},
                new Cities { Id = 341, Name = "GALAPA"},
                new Cities { Id = 342, Name = "JUAN DE ACOSTA"},
                new Cities { Id = 343, Name = "LURUACO"},
                new Cities { Id = 344, Name = "MALAMBO"},
                new Cities { Id = 345, Name = "MANATÍ"},
                new Cities { Id = 346, Name = "PALMAR DE VARELA"},
                new Cities { Id = 347, Name = "PIOJÓ"},
                new Cities { Id = 348, Name = "POLONUEVO"},
                new Cities { Id = 349, Name = "PONEDERA"},
                new Cities { Id = 350, Name = "PUERTO COLOMBIA"},
                new Cities { Id = 351, Name = "REPELÓN"},
                new Cities { Id = 352, Name = "SABANAGRANDE"},
                new Cities { Id = 353, Name = "SABANALARGA"},
                new Cities { Id = 354, Name = "SANTA LUCÍA"},
                new Cities { Id = 355, Name = "SANTO TOMÁS"},
                new Cities { Id = 356, Name = "SOLEDAD"},
                new Cities { Id = 357, Name = "SUÁN"},
                new Cities { Id = 358, Name = "TUBARÁ"},
                new Cities { Id = 359, Name = "USIACURÍ"},
                new Cities { Id = 360, Name = "CARTAGENA"},
                new Cities { Id = 361, Name = "ACHÍ"},
                new Cities { Id = 362, Name = "ALTOS DEL ROSARIO"},
                new Cities { Id = 363, Name = "ARENAL"},
                new Cities { Id = 364, Name = "ARJONA"},
                new Cities { Id = 365, Name = "ARROYOHONDO"},
                new Cities { Id = 366, Name = "BARRANCO DE LOBA"},
                new Cities { Id = 367, Name = "CALAMAR"},
                new Cities { Id = 368, Name = "CANTAGALLO"},
                new Cities { Id = 369, Name = "CICUTO"},
                new Cities { Id = 370, Name = "CÓRDOBA"},
                new Cities { Id = 371, Name = "CLEMENCIA"},
                new Cities { Id = 372, Name = "EL CARMEN DE BOLÍVAR"},
                new Cities { Id = 373, Name = "EL GUAMO"},
                new Cities { Id = 374, Name = "EL PEÑÓN"},
                new Cities { Id = 375, Name = "HATILLO DE LOBA"},
                new Cities { Id = 376, Name = "MAGANGUE"},
                new Cities { Id = 377, Name = "MAHATES"},
                new Cities { Id = 378, Name = "MARGARITA"},
                new Cities { Id = 379, Name = "MARÍA LA BAJA"},
                new Cities { Id = 380, Name = "MONTECRISTO"},
                new Cities { Id = 381, Name = "MOMPÓS"},
                new Cities { Id = 382, Name = "MORALES"},
                new Cities { Id = 383, Name = "PINILLOS"},
                new Cities { Id = 384, Name = "REGIDOR"},
                new Cities { Id = 385, Name = "RÍO VIEJO"},
                new Cities { Id = 386, Name = "SAN CRISTÓBAL"},
                new Cities { Id = 387, Name = "SAN ESTANISLAO"},
                new Cities { Id = 388, Name = "SAN FERNANDO"},
                new Cities { Id = 389, Name = "SAN JACINTO"},
                new Cities { Id = 390, Name = "SAN JACINTO DEL CAUCA"},
                new Cities { Id = 391, Name = "SAN JUAN NEPOMUCENO"},
                new Cities { Id = 392, Name = "SAN MARTÍN DE LOBA"},
                new Cities { Id = 393, Name = "SAN PABLO"},
                new Cities { Id = 394, Name = "SANTA CATALINA"},
                new Cities { Id = 395, Name = "SANTA ROSA"},
                new Cities { Id = 396, Name = "SANTA ROSA DEL SUR"},
                new Cities { Id = 397, Name = "SIMITÍ"},
                new Cities { Id = 398, Name = "SOPLAVIENTO"},
                new Cities { Id = 399, Name = "TALAIGUA NUEVO"},
                new Cities { Id = 400, Name = "TIQUISIO (PUERTO RICO)"},
                new Cities { Id = 401, Name = "TURBACO"},
                new Cities { Id = 402, Name = "TURBANÁ"},
                new Cities { Id = 403, Name = "VILLANUEVA"},
                new Cities { Id = 404, Name = "ZAMBRANO"},
                new Cities { Id = 405, Name = "TUNJA"},
                new Cities { Id = 406, Name = "ALMEIDA"},
                new Cities { Id = 407, Name = "AQUITANIA"},
                new Cities { Id = 408, Name = "ARCABUCO"},
                new Cities { Id = 409, Name = "BELÉN"},
                new Cities { Id = 410, Name = "BERBEO"},
                new Cities { Id = 411, Name = "BETEITIVA"},
                new Cities { Id = 412, Name = "BOAVITA"},
                new Cities { Id = 413, Name = "BOYACÁ"},
                new Cities { Id = 414, Name = "BRISEÑO"},
                new Cities { Id = 415, Name = "BUENAVISTA"},
                new Cities { Id = 416, Name = "BUSBANZÁ"},
                new Cities { Id = 417, Name = "CALDAS"},
                new Cities { Id = 418, Name = "CAMPOHERMOSO"},
                new Cities { Id = 419, Name = "CERINZA"},
                new Cities { Id = 420, Name = "CHINAVITA"},
                new Cities { Id = 421, Name = "CHIQUINQUIRÁ"},
                new Cities { Id = 422, Name = "CHISCAS"},
                new Cities { Id = 423, Name = "CHITA"},
                new Cities { Id = 424, Name = "CHITARANQUE"},
                new Cities { Id = 425, Name = "CHIVATÁ"},
                new Cities { Id = 426, Name = "CIÉNAGA"},
                new Cities { Id = 427, Name = "CÓMBITA"},
                new Cities { Id = 428, Name = "COPER"},
                new Cities { Id = 429, Name = "CORRALES"},
                new Cities { Id = 430, Name = "COVARACHIA"},
                new Cities { Id = 431, Name = "CUBAR"},
                new Cities { Id = 432, Name = "CUCAITA"},
                new Cities { Id = 433, Name = "CUITIVA"},
                new Cities { Id = 434, Name = "CHÍQUIZA"},
                new Cities { Id = 435, Name = "CHIVOR"},
                new Cities { Id = 436, Name = "DUITAMA"},
                new Cities { Id = 437, Name = "EL COCUY"},
                new Cities { Id = 438, Name = "EL ESPINO"},
                new Cities { Id = 439, Name = "FIRAVITOBA"},
                new Cities { Id = 440, Name = "FLORESTA"},
                new Cities { Id = 441, Name = "GACHANTIVÁ"},
                new Cities { Id = 442, Name = "GÁMEZA"},
                new Cities { Id = 443, Name = "GARAGOA"},
                new Cities { Id = 444, Name = "GUACAMAYAS"},
                new Cities { Id = 445, Name = "GUATEQUE"},
                new Cities { Id = 446, Name = "GUAYATÁ"},
                new Cities { Id = 447, Name = "GUICÁN"},
                new Cities { Id = 448, Name = "IZA"},
                new Cities { Id = 449, Name = "JENESANO"},
                new Cities { Id = 450, Name = "JERICÓ"},
                new Cities { Id = 451, Name = "LABRANZAGRANDE"},
                new Cities { Id = 452, Name = "LA CAPILLA"},
                new Cities { Id = 453, Name = "LA VICTORIA"},
                new Cities { Id = 454, Name = "LA UBITA"},
                new Cities { Id = 455, Name = "VILLA DE LEYVA"},
                new Cities { Id = 456, Name = "MACANAL"},
                new Cities { Id = 457, Name = "MARIPÍ"},
                new Cities { Id = 458, Name = "MIRAFLORES"},
                new Cities { Id = 459, Name = "MONGUA"},
                new Cities { Id = 460, Name = "MONGUÍ"},
                new Cities { Id = 461, Name = "MONIQUIRÁ"},
                new Cities { Id = 462, Name = "MOTAVITA"},
                new Cities { Id = 463, Name = "MUZO"},
                new Cities { Id = 464, Name = "NOBSA"},
                new Cities { Id = 465, Name = "NUEVO COLÓN"},
                new Cities { Id = 466, Name = "OICATÁ"},
                new Cities { Id = 467, Name = "OTANCHE"},
                new Cities { Id = 468, Name = "PACHAVITA"},
                new Cities { Id = 469, Name = "PÁEZ"},
                new Cities { Id = 470, Name = "PAIPA"},
                new Cities { Id = 471, Name = "PAJARITO"},
                new Cities { Id = 472, Name = "PANQUEBA"},
                new Cities { Id = 473, Name = "PAUNA"},
                new Cities { Id = 474, Name = "PAYA"},
                new Cities { Id = 475, Name = "PAZ DE RÍO"},
                new Cities { Id = 476, Name = "PESCA"},
                new Cities { Id = 477, Name = "PISVA"},
                new Cities { Id = 478, Name = "PUERTO BOYACÁ"},
                new Cities { Id = 479, Name = "QUÍPAMA"},
                new Cities { Id = 480, Name = "RAMIQUIRÍ"},
                new Cities { Id = 481, Name = "RÁQUIRA"},
                new Cities { Id = 482, Name = "RONDÓN"},
                new Cities { Id = 483, Name = "SABOYÁ"},
                new Cities { Id = 484, Name = "SÁCHICA"},
                new Cities { Id = 485, Name = "SAMACÁ"},
                new Cities { Id = 486, Name = "SAN EDUARDO"},
                new Cities { Id = 487, Name = "SAN JOSÉ DE PARE"},
                new Cities { Id = 488, Name = "SAN LUIS DE GACENO"},
                new Cities { Id = 489, Name = "SAN MATEO"},
                new Cities { Id = 490, Name = "SAN MIGUEL DE SEMA"},
                new Cities { Id = 491, Name = "SAN PABLO DE BORBUR"},
                new Cities { Id = 492, Name = "SANTANA"},
                new Cities { Id = 493, Name = "SANTA MARÍA"},
                new Cities { Id = 494, Name = "SANTA ROSA DE VITERBO"},
                new Cities { Id = 495, Name = "SANTA SOFÍA"},
                new Cities { Id = 496, Name = "SATIVANORTE"},
                new Cities { Id = 497, Name = "SATIVASUR"},
                new Cities { Id = 498, Name = "SIACHOQUE"},
                new Cities { Id = 499, Name = "SOATÁ"},
                new Cities { Id = 500, Name = "SOCOTÁ"},
                new Cities { Id = 501, Name = "SOCHA"},
                new Cities { Id = 502, Name = "SOGAMOSO"},
                new Cities { Id = 503, Name = "SOMONDOCO"},
                new Cities { Id = 504, Name = "SORA"},
                new Cities { Id = 505, Name = "SOTAQUIRÁ"},
                new Cities { Id = 506, Name = "SORACÁ"},
                new Cities { Id = 507, Name = "SUSACÓN"},
                new Cities { Id = 508, Name = "SUTAMARCHÁN"},
                new Cities { Id = 509, Name = "SUTATENZA"},
                new Cities { Id = 510, Name = "TASCO"},
                new Cities { Id = 511, Name = "TENZA"},
                new Cities { Id = 512, Name = "TIBANÁ"},
                new Cities { Id = 513, Name = "TIBASOSA"},
                new Cities { Id = 514, Name = "TINJACÁ"},
                new Cities { Id = 515, Name = "TIPACOQUE"},
                new Cities { Id = 516, Name = "TOCA"},
                new Cities { Id = 517, Name = "TOGUÍ"},
                new Cities { Id = 518, Name = "TÓPAGA"},
                new Cities { Id = 519, Name = "TOTA"},
                new Cities { Id = 520, Name = "TUNUNGUA"},
                new Cities { Id = 521, Name = "TURMEQUÉ"},
                new Cities { Id = 522, Name = "TUTA"},
                new Cities { Id = 523, Name = "TUTAZÁ"},
                new Cities { Id = 524, Name = "ÚMBITA"},
                new Cities { Id = 525, Name = "VENTAQUEMADA"},
                new Cities { Id = 526, Name = "VIRACACHÁ"},
                new Cities { Id = 527, Name = "ZETAQUIRÁ"},
                new Cities { Id = 528, Name = "MANIZALES"},
                new Cities { Id = 529, Name = "AGUADAS"},
                new Cities { Id = 530, Name = "ANSERMA"},
                new Cities { Id = 531, Name = "ARANZAZU"},
                new Cities { Id = 532, Name = "BELALCÁZAR"},
                new Cities { Id = 533, Name = "CHINCHINA"},
                new Cities { Id = 534, Name = "FILADELFIA"},
                new Cities { Id = 535, Name = "LA DORADA"},
                new Cities { Id = 536, Name = "LA MERCED"},
                new Cities { Id = 537, Name = "MANZANARES"},
                new Cities { Id = 538, Name = "MARMATO"},
                new Cities { Id = 539, Name = "MARQUETALIA"},
                new Cities { Id = 540, Name = "MARULANDA"},
                new Cities { Id = 541, Name = "NEIRA"},
                new Cities { Id = 542, Name = "PÁCORA"},
                new Cities { Id = 543, Name = "PALESTINA"},
                new Cities { Id = 544, Name = "PENSILVANIA"},
                new Cities { Id = 545, Name = "RIOSUCIO"},
                new Cities { Id = 546, Name = "RISARALDA"},
                new Cities { Id = 547, Name = "SALAMINA"},
                new Cities { Id = 548, Name = "SAMANÁ"},
                new Cities { Id = 549, Name = "SAN JOSÉ"},
                new Cities { Id = 550, Name = "SUPÍA"},
                new Cities { Id = 551, Name = "VICTORIA"},
                new Cities { Id = 552, Name = "VILLAMARÍA"},
                new Cities { Id = 553, Name = "VITERBO"},
                new Cities { Id = 554, Name = "FLORENCIA"},
                new Cities { Id = 555, Name = "ALBANIA"},
                new Cities { Id = 556, Name = "BELÉN DE LOS ANDAQUÍES"},
                new Cities { Id = 557, Name = "CARTAGENA DEL CHAIRÁ"},
                new Cities { Id = 558, Name = "CURILLO"},
                new Cities { Id = 559, Name = "EL DONCELLO"},
                new Cities { Id = 560, Name = "EL PAUJIL"},
                new Cities { Id = 561, Name = "LA MONTAÑITA"},
                new Cities { Id = 562, Name = "MILÁN"},
                new Cities { Id = 563, Name = "MORELIA"},
                new Cities { Id = 564, Name = "PUERTO RICO"},
                new Cities { Id = 565, Name = "SAN JOSÉ DEL FRAGUA"},
                new Cities { Id = 566, Name = "SAN VICENTE DEL CAGUÁN"},
                new Cities { Id = 567, Name = "SOLANO"},
                new Cities { Id = 568, Name = "SOLITA"},
                new Cities { Id = 569, Name = "VALPARAÍSO"},
                new Cities { Id = 570, Name = "YOPAL"},
                new Cities { Id = 571, Name = "AGUAZUL"},
                new Cities { Id = 572, Name = "CHAMEZA"},
                new Cities { Id = 573, Name = "HATO COROZAL"},
                new Cities { Id = 574, Name = "LA SALINA"},
                new Cities { Id = 575, Name = "MANÍ"},
                new Cities { Id = 576, Name = "MONTERREY"},
                new Cities { Id = 577, Name = "NUNCHÍA"},
                new Cities { Id = 578, Name = "OROCUÉ"},
                new Cities { Id = 579, Name = "PAZ DE ARIPORO"},
                new Cities { Id = 580, Name = "PORE"},
                new Cities { Id = 581, Name = "RECETOR"},
                new Cities { Id = 582, Name = "SABALARGA"},
                new Cities { Id = 583, Name = "SÁCAMA"},
                new Cities { Id = 584, Name = "SAN LUIS DE PALENQUE"},
                new Cities { Id = 585, Name = "TÁMARA"},
                new Cities { Id = 586, Name = "TAURAMENA"},
                new Cities { Id = 587, Name = "TRINIDAD"},
                new Cities { Id = 588, Name = "VILLANUEVA"},
                new Cities { Id = 589, Name = "POPAYÁN"},
                new Cities { Id = 590, Name = "ALMAGUER"},
                new Cities { Id = 591, Name = "ARGELIA"},
                new Cities { Id = 592, Name = "BALBOA"},
                new Cities { Id = 593, Name = "BOLÍVAR"},
                new Cities { Id = 594, Name = "BUENOS AIRES"},
                new Cities { Id = 595, Name = "CAJIBÍO"},
                new Cities { Id = 596, Name = "CALDONO"},
                new Cities { Id = 597, Name = "CALOTO"},
                new Cities { Id = 598, Name = "CORINTO"},
                new Cities { Id = 599, Name = "EL TAMBO"},
                new Cities { Id = 600, Name = "FLORENCIA"},
                new Cities { Id = 601, Name = "GUAPI"},
                new Cities { Id = 602, Name = "INZÁ"},
                new Cities { Id = 603, Name = "JAMBALÓ"},
                new Cities { Id = 604, Name = "LA SIERRA"},
                new Cities { Id = 605, Name = "LA VEGA"},
                new Cities { Id = 606, Name = "LÓPEZ (MICAY)"},
                new Cities { Id = 607, Name = "MERCADERES"},
                new Cities { Id = 608, Name = "MIRANDA"},
                new Cities { Id = 609, Name = "MORALES"},
                new Cities { Id = 610, Name = "PADILLA"},
                new Cities { Id = 611, Name = "PÁEZ (BELALCAZAR)"},
                new Cities { Id = 612, Name = "PATÍA (EL BORDO)"},
                new Cities { Id = 613, Name = "PIAMONTE"},
                new Cities { Id = 614, Name = "PIENDAMÓ"},
                new Cities { Id = 615, Name = "PUERTO TEJADA"},
                new Cities { Id = 616, Name = "PURACÉ (COCONUCO)"},
                new Cities { Id = 617, Name = "ROSAS"},
                new Cities { Id = 618, Name = "SAN SEBASTIÁN"},
                new Cities { Id = 619, Name = "SANTANDER DE QUILICHAO"},
                new Cities { Id = 620, Name = "SANTA ROSA"},
                new Cities { Id = 621, Name = "SILVIA"},
                new Cities { Id = 622, Name = "SOTARÁ (PAISPAMBA)"},
                new Cities { Id = 623, Name = "SUÁREZ"},
                new Cities { Id = 624, Name = "TIMBÍO"},
                new Cities { Id = 625, Name = "TIMBIQUÍ"},
                new Cities { Id = 626, Name = "TORIBÍO"},
                new Cities { Id = 627, Name = "TOTORO"},
                new Cities { Id = 628, Name = "VALLEDUPAR"},
                new Cities { Id = 629, Name = "AGUACHICA"},
                new Cities { Id = 630, Name = "AGUSTÍN CODAZZI"},
                new Cities { Id = 631, Name = "ASTREA"},
                new Cities { Id = 632, Name = "BECERRIL"},
                new Cities { Id = 633, Name = "BOSCONIA"},
                new Cities { Id = 634, Name = "CHIMICHAGUA"},
                new Cities { Id = 635, Name = "CHIRIGUANÁ"},
                new Cities { Id = 636, Name = "CURUMANÍ"},
                new Cities { Id = 637, Name = "EL COPEY"},
                new Cities { Id = 638, Name = "EL PASO"},
                new Cities { Id = 639, Name = "GAMARRA"},
                new Cities { Id = 640, Name = "GONZÁLEZ"},
                new Cities { Id = 641, Name = "LA GLORIA"},
                new Cities { Id = 642, Name = "LA JAGUA DE IBIRICO"},
                new Cities { Id = 643, Name = "MANAURE BALCÓN CESAR"},
                new Cities { Id = 644, Name = "PAILITAS"},
                new Cities { Id = 645, Name = "PELAYA"},
                new Cities { Id = 646, Name = "PUEBLO BELLO"},
                new Cities { Id = 647, Name = "RÍO DE ORO"},
                new Cities { Id = 648, Name = "LA PAZ (ROBLES)"},
                new Cities { Id = 649, Name = "SAN ALBERTO"},
                new Cities { Id = 650, Name = "SAN DIEGO"},
                new Cities { Id = 651, Name = "SAN MARTÍN"},
                new Cities { Id = 652, Name = "TAMALAMEQUE"},
                new Cities { Id = 653, Name = "MONTERÍA"},
                new Cities { Id = 654, Name = "AYAPEL"},
                new Cities { Id = 655, Name = "BUENAVISTA"},
                new Cities { Id = 656, Name = "CANALETE"},
                new Cities { Id = 657, Name = "CERETÉ"},
                new Cities { Id = 658, Name = "CHIMA"},
                new Cities { Id = 659, Name = "CHINÚ"},
                new Cities { Id = 660, Name = "CIÉNAGA DE ORO"},
                new Cities { Id = 661, Name = "COTORRA"},
                new Cities { Id = 662, Name = "LA APARTADA (FRONTERA)"},
                new Cities { Id = 663, Name = "LORICA"},
                new Cities { Id = 664, Name = "LOS CÓRDOBAS"},
                new Cities { Id = 665, Name = "MOMIL"},
                new Cities { Id = 666, Name = "MONTELÍBANO"},
                new Cities { Id = 667, Name = "MONITOS"},
                new Cities { Id = 668, Name = "PLANETA RICA"},
                new Cities { Id = 669, Name = "PUEBLO NUEVO"},
                new Cities { Id = 670, Name = "PUERTO ESCONDIDO"},
                new Cities { Id = 671, Name = "PUERTO LIBERTADOR"},
                new Cities { Id = 672, Name = "PURÍSIMA"},
                new Cities { Id = 673, Name = "SAHAGÚN"},
                new Cities { Id = 674, Name = "SAN ANDRÉS SOTAVENTO"},
                new Cities { Id = 675, Name = "SAN ANTERO"},
                new Cities { Id = 676, Name = "SAN BERNARDO DEL VIENTO"},
                new Cities { Id = 677, Name = "SAN CARLOS"},
                new Cities { Id = 678, Name = "SAN PELAYO"},
                new Cities { Id = 679, Name = "TIERRALTA"},
                new Cities { Id = 680, Name = "VALENCIA"},
                new Cities { Id = 681, Name = "SANTAFÉ DE BOGOTÁ"},
                new Cities { Id = 682, Name = "AGUA DE DIOS"},
                new Cities { Id = 683, Name = "ALBÁN"},
                new Cities { Id = 684, Name = "ANAPOIMA"},
                new Cities { Id = 685, Name = "ANOLAIMA"},
                new Cities { Id = 686, Name = "ARBELÁEZ"},
                new Cities { Id = 687, Name = "BELTRÁN"},
                new Cities { Id = 688, Name = "BITUIMA"},
                new Cities { Id = 689, Name = "BOJACÁ"},
                new Cities { Id = 690, Name = "CABRERA"},
                new Cities { Id = 691, Name = "CACHIPAY"},
                new Cities { Id = 692, Name = "CAJICÁ"},
                new Cities { Id = 693, Name = "CAPARRAPÍ"},
                new Cities { Id = 694, Name = "CÁQUEZA"},
                new Cities { Id = 695, Name = "CARMEN DE CARUPA"},
                new Cities { Id = 696, Name = "CHAGUANÍ"},
                new Cities { Id = 697, Name = "CHÍA"},
                new Cities { Id = 698, Name = "CHIPAQUE"},
                new Cities { Id = 699, Name = "CHOACHÍ"},
                new Cities { Id = 700, Name = "CHOCONTÁ"},
                new Cities { Id = 701, Name = "COGUA"},
                new Cities { Id = 702, Name = "COTA"},
                new Cities { Id = 703, Name = "CUCUNUBÁ"},
                new Cities { Id = 704, Name = "EL COLEGIO"},
                new Cities { Id = 705, Name = "EL PEÑÓN"},
                new Cities { Id = 706, Name = "EL ROSAL"},
                new Cities { Id = 707, Name = "FACATATIVÁ"},
                new Cities { Id = 708, Name = "FÓMEQUE"},
                new Cities { Id = 709, Name = "FOSCA"},
                new Cities { Id = 710, Name = "FUNZA"},
                new Cities { Id = 711, Name = "FÚQUENE"},
                new Cities { Id = 712, Name = "FUSAGASUGÁ"},
                new Cities { Id = 713, Name = "GACHALÁ"},
                new Cities { Id = 714, Name = "GACHANCIPÁ"},
                new Cities { Id = 715, Name = "GACHETÁ"},
                new Cities { Id = 716, Name = "GAMA"},
                new Cities { Id = 717, Name = "GIRARDOT"},
                new Cities { Id = 718, Name = "GRANADA"},
                new Cities { Id = 719, Name = "GUACHETÁ"},
                new Cities { Id = 720, Name = "GUADUAS"},
                new Cities { Id = 721, Name = "GUASCA"},
                new Cities { Id = 722, Name = "GUATAQUÍ"},
                new Cities { Id = 723, Name = "GUATAVITA"},
                new Cities { Id = 724, Name = "GUAYABAL DE SÍQUIMA"},
                new Cities { Id = 725, Name = "GUAYABETAL"},
                new Cities { Id = 726, Name = "GUTIÉRREZ"},
                new Cities { Id = 727, Name = "JERUSALÉN"},
                new Cities { Id = 728, Name = "JUNÍN"},
                new Cities { Id = 729, Name = "LA CALERA"},
                new Cities { Id = 730, Name = "LA MESA"},
                new Cities { Id = 731, Name = "LA PALMA"},
                new Cities { Id = 732, Name = "LA PEÑA"},
                new Cities { Id = 733, Name = "LA VEGA"},
                new Cities { Id = 734, Name = "LENGUAZAQUE"},
                new Cities { Id = 735, Name = "MACHETÁ"},
                new Cities { Id = 736, Name = "MADRID"},
                new Cities { Id = 737, Name = "MANTA"},
                new Cities { Id = 738, Name = "MEDINA"},
                new Cities { Id = 739, Name = "MOSQUERA"},
                new Cities { Id = 740, Name = "NARIÑO"},
                new Cities { Id = 741, Name = "NEMOCÓN"},
                new Cities { Id = 742, Name = "NILO"},
                new Cities { Id = 743, Name = "NIMAIMA"},
                new Cities { Id = 744, Name = "NOCAIMA"},
                new Cities { Id = 745, Name = "VENECIA (OSPINA PÉREZ)"},
                new Cities { Id = 746, Name = "PACHO"},
                new Cities { Id = 747, Name = "PAIME"},
                new Cities { Id = 748, Name = "PANDI"},
                new Cities { Id = 749, Name = "PARATEBUENO"},
                new Cities { Id = 750, Name = "PASCA"},
                new Cities { Id = 751, Name = "PUERTO SALGAR"},
                new Cities { Id = 752, Name = "PULÍ"},
                new Cities { Id = 753, Name = "QUEBRADANEGRA"},
                new Cities { Id = 754, Name = "QUETAME"},
                new Cities { Id = 755, Name = "QUIPILE"},
                new Cities { Id = 756, Name = "RAFAEL"},
                new Cities { Id = 757, Name = "RICAURTE"},
                new Cities { Id = 758, Name = "SAN ANTONIO DE TEQUENDAMA"},
                new Cities { Id = 759, Name = "SAN BERNARDO"},
                new Cities { Id = 760, Name = "SAN CAYETANO"},
                new Cities { Id = 761, Name = "SAN FRANCISCO"},
                new Cities { Id = 762, Name = "SAN JUAN DE RIOSECO"},
                new Cities { Id = 763, Name = "SASAIMA"},
                new Cities { Id = 764, Name = "SESQUILÉ"},
                new Cities { Id = 765, Name = "SIBATE"},
                new Cities { Id = 766, Name = "SILVANIA"},
                new Cities { Id = 767, Name = "SIMIJACA"},
                new Cities { Id = 768, Name = "SOACHA"},
                new Cities { Id = 769, Name = "SOPÓ"},
                new Cities { Id = 770, Name = "SUBACHOQUE"},
                new Cities { Id = 771, Name = "SUESCA"},
                new Cities { Id = 772, Name = "SUPATÁ"},
                new Cities { Id = 773, Name = "SUSA"},
                new Cities { Id = 774, Name = "SUTATAUSA"},
                new Cities { Id = 775, Name = "TABIO"},
                new Cities { Id = 776, Name = "TAUSA"},
                new Cities { Id = 777, Name = "TENA"},
                new Cities { Id = 778, Name = "TENJO"},
                new Cities { Id = 779, Name = "TIBACUY"},
                new Cities { Id = 780, Name = "TIBIRITÁ"},
                new Cities { Id = 781, Name = "TOCAIMA"},
                new Cities { Id = 782, Name = "TOCANCIPÁ"},
                new Cities { Id = 783, Name = "TOPAIPÍ"},
                new Cities { Id = 784, Name = "UBALÁ"},
                new Cities { Id = 785, Name = "UBAQUE"},
                new Cities { Id = 786, Name = "UBATÉ"},
                new Cities { Id = 787, Name = "UNE"},
                new Cities { Id = 788, Name = "ÚTICA"},
                new Cities { Id = 789, Name = "VERGARA"},
                new Cities { Id = 790, Name = "VIANÍ"},
                new Cities { Id = 791, Name = "VILLAGÓMEZ"},
                new Cities { Id = 792, Name = "VILLAPINZÓN"},
                new Cities { Id = 793, Name = "VILLETA"},
                new Cities { Id = 794, Name = "VIOTÁ"},
                new Cities { Id = 795, Name = "YACOPÍ"},
                new Cities { Id = 796, Name = "ZIPACÓN"},
                new Cities { Id = 797, Name = "ZIPAQUIRÁ"},
                new Cities { Id = 798, Name = "QUIBDÓ"},
                new Cities { Id = 799, Name = "ACANDÍ"},
                new Cities { Id = 800, Name = "ALTO BAUDÓ (PIE DE PATO)"},
                new Cities { Id = 801, Name = "ATRATO (YUTO)"},
                new Cities { Id = 802, Name = "BAGADÓ"},
                new Cities { Id = 803, Name = "BAHÍA SOLANO (MÚTIS)"},
                new Cities { Id = 804, Name = "BAJO BAUDÓ (PIZARRO)"},
                new Cities { Id = 805, Name = "BOJAYÁ (BELLAVISTA)"},
                new Cities { Id = 806, Name = "CANTÓN DE SAN PABLO"},
                new Cities { Id = 807, Name = "CONDOTO"},
                new Cities { Id = 808, Name = "EL CARMEN"},
                new Cities { Id = 809, Name = "EL LITORAL DE SAN JUAN"},
                new Cities { Id = 810, Name = "ITSMINA"},
                new Cities { Id = 811, Name = "JURADÓ"},
                new Cities { Id = 812, Name = "LLORÓ"},
                new Cities { Id = 813, Name = "NÓVITA"},
                new Cities { Id = 814, Name = "NUQUÍ"},
                new Cities { Id = 815, Name = "RIOSUCIO"},
                new Cities { Id = 816, Name = "SAN JOSÉ DEL PALMAR"},
                new Cities { Id = 817, Name = "SIPÍ"},
                new Cities { Id = 818, Name = "TADÓ"},
                new Cities { Id = 819, Name = "UNGUÍA"},
                new Cities { Id = 820, Name = "PUERTO INÍRIDA"},
                new Cities { Id = 821, Name = "SAN JOSÉ DEL GUAVIARE"},
                new Cities { Id = 822, Name = "CALAMAR"},
                new Cities { Id = 823, Name = "EL RETORNO"},
                new Cities { Id = 824, Name = "MIRAFLORES"},
                new Cities { Id = 825, Name = "NEIVA"},
                new Cities { Id = 826, Name = "ACEVEDO"},
                new Cities { Id = 827, Name = "AGRADO"},
                new Cities { Id = 828, Name = "AIPE"},
                new Cities { Id = 829, Name = "ALGECIRAS"},
                new Cities { Id = 830, Name = "ALTAMIRA"},
                new Cities { Id = 831, Name = "BARAYA"},
                new Cities { Id = 832, Name = "CAMPOALEGRE"},
                new Cities { Id = 833, Name = "COLOMBIA"},
                new Cities { Id = 834, Name = "ELÍAS"},
                new Cities { Id = 835, Name = "GARZÓN"},
                new Cities { Id = 836, Name = "GIGANTE"},
                new Cities { Id = 837, Name = "GUADALUPE"},
                new Cities { Id = 838, Name = "HOBO"},
                new Cities { Id = 839, Name = "IQUIRA"},
                new Cities { Id = 840, Name = "ISNOS"},
                new Cities { Id = 841, Name = "LA ARGENTINA"},
                new Cities { Id = 842, Name = "LA PLATA"},
                new Cities { Id = 843, Name = "NÁTAGA"},
                new Cities { Id = 844, Name = "OPORAPA"},
                new Cities { Id = 845, Name = "PAICOL"},
                new Cities { Id = 846, Name = "PALERMO"},
                new Cities { Id = 847, Name = "PALESTINA"},
                new Cities { Id = 848, Name = "PITAL"},
                new Cities { Id = 849, Name = "PITALITO"},
                new Cities { Id = 850, Name = "RIVERA"},
                new Cities { Id = 851, Name = "SALADOBLANCO"},
                new Cities { Id = 852, Name = "SAN AGUSTÍN"},
                new Cities { Id = 853, Name = "SANTA MARÍA"},
                new Cities { Id = 854, Name = "SUAZÁ"},
                new Cities { Id = 855, Name = "TARQUI"},
                new Cities { Id = 856, Name = "TESALIA"},
                new Cities { Id = 857, Name = "TELLO"},
                new Cities { Id = 858, Name = "TERUEL"},
                new Cities { Id = 859, Name = "TIMANÁ"},
                new Cities { Id = 860, Name = "VILLAVIEJA"},
                new Cities { Id = 861, Name = "YAGUARÁ"},
                new Cities { Id = 862, Name = "RIOHACHA"},
                new Cities { Id = 863, Name = "BARRANCAS"},
                new Cities { Id = 864, Name = "DIBULLA"},
                new Cities { Id = 865, Name = "DISTRACCIÓN"},
                new Cities { Id = 866, Name = "EL MOLINO"},
                new Cities { Id = 867, Name = "FONSECA"},
                new Cities { Id = 868, Name = "HATONUEVO"},
                new Cities { Id = 869, Name = "MAICAO"},
                new Cities { Id = 870, Name = "MANAURE"},
                new Cities { Id = 871, Name = "SAN JUAN DEL CESAR"},
                new Cities { Id = 872, Name = "URIBÍA"},
                new Cities { Id = 873, Name = "URUMITA"},
                new Cities { Id = 874, Name = "VILLANUEVA"},
                new Cities { Id = 875, Name = "SANTA MARTA"},
                new Cities { Id = 876, Name = "ARACATACA"},
                new Cities { Id = 877, Name = "ARIGUANÍ (EL DIFÍCIL)"},
                new Cities { Id = 878, Name = "CERRO SAN ANTONIO"},
                new Cities { Id = 879, Name = "CHIVOLO"},
                new Cities { Id = 880, Name = "CIÉNAGA"},
                new Cities { Id = 881, Name = "EL BANCO"},
                new Cities { Id = 882, Name = "EL PIÑÓN"},
                new Cities { Id = 883, Name = "EL RETÉN"},
                new Cities { Id = 884, Name = "FUNDACIÓN"},
                new Cities { Id = 885, Name = "GUAMAL"},
                new Cities { Id = 886, Name = "PEDRAZA"},
                new Cities { Id = 887, Name = "PIJIÑO DEL CARMEN"},
                new Cities { Id = 888, Name = "PIVIJAY"},
                new Cities { Id = 889, Name = "PLATO"},
                new Cities { Id = 890, Name = "PUBLOVIEJO"},
                new Cities { Id = 891, Name = "REMOLINO"},
                new Cities { Id = 892, Name = "SALAMINA"},
                new Cities { Id = 893, Name = "SAN SEBASTIÁN DE BUUENAVISTA"},
                new Cities { Id = 894, Name = "SAN ZENÓN"},
                new Cities { Id = 895, Name = "SANTA ANA"},
                new Cities { Id = 896, Name = "SITIONUEVO"},
                new Cities { Id = 897, Name = "TENERIFE"},
                new Cities { Id = 898, Name = "VILLAVICENCIO"},
                new Cities { Id = 899, Name = "ACACIAS"},
                new Cities { Id = 900, Name = "BARRANCA DE UPÍA"},
                new Cities { Id = 901, Name = "CABUYARO"},
                new Cities { Id = 902, Name = "CASTILLA LA NUEVA"},
                new Cities { Id = 903, Name = "CUBARRAL"},
                new Cities { Id = 904, Name = "CUMARAL"},
                new Cities { Id = 905, Name = "EL CALVARIO"},
                new Cities { Id = 906, Name = "EL CASTILLO"},
                new Cities { Id = 907, Name = "EL DORADO"},
                new Cities { Id = 908, Name = "FUENTE DE ORO"},
                new Cities { Id = 909, Name = "GRANADA"},
                new Cities { Id = 910, Name = "GUAMAL"},
                new Cities { Id = 911, Name = "MAPIRIPÁN"},
                new Cities { Id = 912, Name = "MESETAS"},
                new Cities { Id = 913, Name = "LA MACARENA"},
                new Cities { Id = 914, Name = "LA URIBE"},
                new Cities { Id = 915, Name = "LEJANÍAS"},
                new Cities { Id = 916, Name = "PUERTO CONCORDIA"},
                new Cities { Id = 917, Name = "PUERTO GAITÁN"},
                new Cities { Id = 918, Name = "PUERTO LÓPEZ"},
                new Cities { Id = 919, Name = "PUERTO LLERAS"},
                new Cities { Id = 920, Name = "PUERTO RICO"},
                new Cities { Id = 921, Name = "RESTREPO"},
                new Cities { Id = 922, Name = "SAN CARLOS DE GUAROA"},
                new Cities { Id = 923, Name = "SAN JUAN DE ARAMA"},
                new Cities { Id = 924, Name = "SAN JUANITO"},
                new Cities { Id = 925, Name = "SAN MARTÍN"},
                new Cities { Id = 926, Name = "VISTAHERMOSA"},
                new Cities { Id = 927, Name = "PASTO"},
                new Cities { Id = 928, Name = "ALBÁN (SAN JOSÉ)"},
                new Cities { Id = 929, Name = "ALDANA"},
                new Cities { Id = 930, Name = "ANCUYÁ"},
                new Cities { Id = 931, Name = "ARBOLEDA (BERRUECOS)"},
                new Cities { Id = 932, Name = "BARBACOAS"},
                new Cities { Id = 933, Name = "BELÉN"},
                new Cities { Id = 934, Name = "BUESACO"},
                new Cities { Id = 935, Name = "COLÓN (GÉNOVA)"},
                new Cities { Id = 936, Name = "CONSACÁ"},
                new Cities { Id = 937, Name = "CONTADERO"},
                new Cities { Id = 938, Name = "CÓRDOBA"},
                new Cities { Id = 939, Name = "CUASPUD (CARLOSAMA)"},
                new Cities { Id = 940, Name = "CUMBAL"},
                new Cities { Id = 941, Name = "CUMBITARÁ"},
                new Cities { Id = 942, Name = "CHACHAGÜI"},
                new Cities { Id = 943, Name = "EL CHARCO"},
                new Cities { Id = 944, Name = "EL ROSARIO"},
                new Cities { Id = 945, Name = "EL TABLÓN"},
                new Cities { Id = 946, Name = "EL TAMBO"},
                new Cities { Id = 947, Name = "FUNES"},
                new Cities { Id = 948, Name = "GUACHUCAL"},
                new Cities { Id = 949, Name = "GUAITARILLA"},
                new Cities { Id = 950, Name = "GUALMATÁN"},
                new Cities { Id = 951, Name = "ILES"},
                new Cities { Id = 952, Name = "IMÚES"},
                new Cities { Id = 953, Name = "IPIALES"},
                new Cities { Id = 954, Name = "LA CRUZ"},
                new Cities { Id = 955, Name = "LA FLORIDA"},
                new Cities { Id = 956, Name = "LA LLANADA"},
                new Cities { Id = 957, Name = "LA TOLA"},
                new Cities { Id = 958, Name = "LA UNIÓN"},
                new Cities { Id = 959, Name = "LEIVA"},
                new Cities { Id = 960, Name = "LINARES"},
                new Cities { Id = 961, Name = "LOS ANDES (SOTOMAYOR)"},
                new Cities { Id = 962, Name = "MAGÜÍ (PAYÁN)"},
                new Cities { Id = 963, Name = "MALLAMA (PIEDRANCHA)"},
                new Cities { Id = 964, Name = "MOSQUERA"},
                new Cities { Id = 965, Name = "OLAYA"},
                new Cities { Id = 966, Name = "OSPINA"},
                new Cities { Id = 967, Name = "FRANCISCO PIZARRO"},
                new Cities { Id = 968, Name = "POLICARPA"},
                new Cities { Id = 969, Name = "POTOSÍ"},
                new Cities { Id = 970, Name = "PROVIDENCIA"},
                new Cities { Id = 971, Name = "PUERRES"},
                new Cities { Id = 972, Name = "PUPIALES"},
                new Cities { Id = 973, Name = "RICAURTE"},
                new Cities { Id = 974, Name = "ROBERTO PAYÁN (SAN JOSÉ)"},
                new Cities { Id = 975, Name = "SAMANIEGO"},
                new Cities { Id = 976, Name = "SANDONÁ"},
                new Cities { Id = 977, Name = "SAN BERNARDO"},
                new Cities { Id = 978, Name = "SAN LORENZO"},
                new Cities { Id = 979, Name = "SAN PABLO"},
                new Cities { Id = 980, Name = "SAN PEDRO DE CARTAGO"},
                new Cities { Id = 981, Name = "SANTA BÁRBARA (ISCUANDÉ)"},
                new Cities { Id = 982, Name = "SANTA CRUZ (GUACHÁVEZ)"},
                new Cities { Id = 983, Name = "SAPUYÉS"},
                new Cities { Id = 984, Name = "TAMINANGO"},
                new Cities { Id = 985, Name = "TANGUA"},
                new Cities { Id = 986, Name = "TUMACO"},
                new Cities { Id = 987, Name = "TÚQUERRES"},
                new Cities { Id = 988, Name = "YACUANQUER"},
                new Cities { Id = 989, Name = "CÚCUTA"},
                new Cities { Id = 990, Name = "ABREGO"},
                new Cities { Id = 991, Name = "ARBOLEDAS"},
                new Cities { Id = 992, Name = "BOCHALEMA"},
                new Cities { Id = 993, Name = "BUCARASICA"},
                new Cities { Id = 994, Name = "CÁCOTA"},
                new Cities { Id = 995, Name = "CÁCHIRA"},
                new Cities { Id = 996, Name = "CHINÁCOTA"},
                new Cities { Id = 997, Name = "CHITAGÁ"},
                new Cities { Id = 998, Name = "CONVENCIÓN"},
                new Cities { Id = 999, Name = "CUCUTILLA"},
                new Cities { Id = 1000, Name = "DURANIA"},
                new Cities { Id = 1001, Name = "EL CARMEN"},
                new Cities { Id = 1002, Name = "EL TARRA"},
                new Cities { Id = 1003, Name = "EL ZULIA"},
                new Cities { Id = 1004, Name = "GRAMALOTE"},
                new Cities { Id = 1005, Name = "HACARÍ"},
                new Cities { Id = 1006, Name = "HERRÁN"},
                new Cities { Id = 1007, Name = "LABATECA"},
                new Cities { Id = 1008, Name = "LA ESPERANZA"},
                new Cities { Id = 1009, Name = "LA PLAYA"},
                new Cities { Id = 1010, Name = "LOS PATIOS"},
                new Cities { Id = 1011, Name = "LOURDES"},
                new Cities { Id = 1012, Name = "MUTISCUA"},
                new Cities { Id = 1013, Name = "OCAÑA"},
                new Cities { Id = 1014, Name = "PAMPLONA"},
                new Cities { Id = 1015, Name = "PAMPLONITA"},
                new Cities { Id = 1016, Name = "PUERTO SANTANDER"},
                new Cities { Id = 1017, Name = "RAGONVALIA"},
                new Cities { Id = 1018, Name = "SALAZAR"},
                new Cities { Id = 1019, Name = "SAN CALIXTO"},
                new Cities { Id = 1020, Name = "SAN CAYETANO"},
                new Cities { Id = 1021, Name = "SANTIAGO"},
                new Cities { Id = 1022, Name = "SARDINATA"},
                new Cities { Id = 1023, Name = "SILOS"},
                new Cities { Id = 1024, Name = "TEORAMA"},
                new Cities { Id = 1025, Name = "TIBÚ"},
                new Cities { Id = 1026, Name = "TOLEDO"},
                new Cities { Id = 1027, Name = "VILLACARO"},
                new Cities { Id = 1028, Name = "VILLA DEL ROSARIO"},
                new Cities { Id = 1029, Name = "MOCOA"},
                new Cities { Id = 1030, Name = "COLÓN"},
                new Cities { Id = 1031, Name = "ORITO"},
                new Cities { Id = 1032, Name = "PUERTO ASÍS"},
                new Cities { Id = 1033, Name = "PUERTO CAICEDO"},
                new Cities { Id = 1034, Name = "PUERTO GUZMÁN"},
                new Cities { Id = 1035, Name = "PUERTO LEGUÍZAMO"},
                new Cities { Id = 1036, Name = "SIBUNDOY"},
                new Cities { Id = 1037, Name = "SAN FRANCISCO"},
                new Cities { Id = 1038, Name = "SAN MIGUEL"},
                new Cities { Id = 1039, Name = "SANTIAGO"},
                new Cities { Id = 1040, Name = "VILLA GAMUEZ (LA HORMIGA)"},
                new Cities { Id = 1041, Name = "VILLA GARZÓN"},
                new Cities { Id = 1042, Name = "ARMENIA"},
                new Cities { Id = 1043, Name = "BUENAVISTA"},
                new Cities { Id = 1044, Name = "CALARCÁ"},
                new Cities { Id = 1045, Name = "CIRCASIA"},
                new Cities { Id = 1046, Name = "CÓRDOBA"},
                new Cities { Id = 1047, Name = "FILANDIA"},
                new Cities { Id = 1048, Name = "GÉNOVA"},
                new Cities { Id = 1049, Name = "LA TEBAIDA"},
                new Cities { Id = 1050, Name = "MONTENEGRO"},
                new Cities { Id = 1051, Name = "PIJAO"},
                new Cities { Id = 1052, Name = "QUIMBAYA"},
                new Cities { Id = 1053, Name = "SALENTO"},
                new Cities { Id = 1054, Name = "PEREIRA"},
                new Cities { Id = 1055, Name = "APÍA"},
                new Cities { Id = 1056, Name = "BALBOA"},
                new Cities { Id = 1057, Name = "BELÉN DE UMBRÍA"},
                new Cities { Id = 1058, Name = "DOS QUEBRADAS"},
                new Cities { Id = 1059, Name = "GUÁTICA"},
                new Cities { Id = 1060, Name = "LA CELIA"},
                new Cities { Id = 1061, Name = "LA VIRGINIA"},
                new Cities { Id = 1062, Name = "MARSELLA"},
                new Cities { Id = 1063, Name = "MISTRATÓ"},
                new Cities { Id = 1064, Name = "PUEBLO RICO"},
                new Cities { Id = 1065, Name = "QUINCHIA"},
                new Cities { Id = 1066, Name = "SANTA ROSA DE CABAL"},
                new Cities { Id = 1067, Name = "SANTUARIO"},
                new Cities { Id = 1068, Name = "SAN ANDRÉS"},
                new Cities { Id = 1069, Name = "PROVIDENCIA"},
                new Cities { Id = 1070, Name = "BUCARAMANGA"},
                new Cities { Id = 1071, Name = "AGUADA"},
                new Cities { Id = 1072, Name = "ALBANIA"},
                new Cities { Id = 1073, Name = "ARATOCA"},
                new Cities { Id = 1074, Name = "BARBOSA"},
                new Cities { Id = 1075, Name = "BARICHARA"},
                new Cities { Id = 1076, Name = "BARRANCABERMEJA"},
                new Cities { Id = 1077, Name = "BETULIA"},
                new Cities { Id = 1078, Name = "BOLÍVAR"},
                new Cities { Id = 1079, Name = "CABRERA"},
                new Cities { Id = 1080, Name = "CALIFORNIA"},
                new Cities { Id = 1081, Name = "CAPITANEJO"},
                new Cities { Id = 1082, Name = "CARCASÍ"},
                new Cities { Id = 1083, Name = "CEPITÁ"},
                new Cities { Id = 1084, Name = "CERRITO"},
                new Cities { Id = 1085, Name = "CHARALÁ"},
                new Cities { Id = 1086, Name = "CHARTA"},
                new Cities { Id = 1087, Name = "CHIMA"},
                new Cities { Id = 1088, Name = "CHIPATÁ"},
                new Cities { Id = 1089, Name = "CIMITARRA"},
                new Cities { Id = 1090, Name = "CONCEPCIÓN"},
                new Cities { Id = 1091, Name = "CONFINES"},
                new Cities { Id = 1092, Name = "CONTRATACIÓN"},
                new Cities { Id = 1093, Name = "COROMORO"},
                new Cities { Id = 1094, Name = "CURITÍ"},
                new Cities { Id = 1095, Name = "EL CARMEN"},
                new Cities { Id = 1096, Name = "EL GUACAMAYO"},
                new Cities { Id = 1097, Name = "EL PEÑÓN"},
                new Cities { Id = 1098, Name = "EL PLAYÓN"},
                new Cities { Id = 1099, Name = "ENCINO"},
                new Cities { Id = 1100, Name = "ENCISO"},
                new Cities { Id = 1101, Name = "FLORIÁN"},
                new Cities { Id = 1102, Name = "FLORIDABLANCA"},
                new Cities { Id = 1103, Name = "GALÁN"},
                new Cities { Id = 1104, Name = "GÁMBITA"},
                new Cities { Id = 1105, Name = "GIRÓN"},
                new Cities { Id = 1106, Name = "GUACA"},
                new Cities { Id = 1107, Name = "GUADALUPE"},
                new Cities { Id = 1108, Name = "GUAPOTÁ"},
                new Cities { Id = 1109, Name = "GUAVATA"},
                new Cities { Id = 1110, Name = "GUEPSA"},
                new Cities { Id = 1111, Name = "HATO"},
                new Cities { Id = 1112, Name = "JESÚS MARÍA"},
                new Cities { Id = 1113, Name = "JORDÁN"},
                new Cities { Id = 1114, Name = "LA BELLEZA"},
                new Cities { Id = 1115, Name = "LANDÁZURI"},
                new Cities { Id = 1116, Name = "LA PAZ"},
                new Cities { Id = 1117, Name = "LEBRIJA"},
                new Cities { Id = 1118, Name = "LOS SANTOS"},
                new Cities { Id = 1119, Name = "MACARAVITA"},
                new Cities { Id = 1120, Name = "MÁLAGA"},
                new Cities { Id = 1121, Name = "MATANZA"},
                new Cities { Id = 1122, Name = "MOGOTES"},
                new Cities { Id = 1123, Name = "MOLAGAVITA"},
                new Cities { Id = 1124, Name = "OCAMONTE"},
                new Cities { Id = 1125, Name = "OIBA"},
                new Cities { Id = 1126, Name = "ONZÁGA"},
                new Cities { Id = 1127, Name = "PALMAR"},
                new Cities { Id = 1128, Name = "PALMAS DEL SOCORRO"},
                new Cities { Id = 1129, Name = "PÁRAMO"},
                new Cities { Id = 1130, Name = "PIE DE CUESTA"},
                new Cities { Id = 1131, Name = "PINCHOTE"},
                new Cities { Id = 1132, Name = "PUENTE NACIONAL"},
                new Cities { Id = 1133, Name = "PUERTO PARRA"},
                new Cities { Id = 1134, Name = "PUERTO WILCHES"},
                new Cities { Id = 1135, Name = "RIONEGRO"},
                new Cities { Id = 1136, Name = "SABANA DE TORRES"},
                new Cities { Id = 1137, Name = "SAN ANDRÉS"},
                new Cities { Id = 1138, Name = "SAN BENITO"},
                new Cities { Id = 1139, Name = "SAN GIL"},
                new Cities { Id = 1140, Name = "SAN JOAQUÍN"},
                new Cities { Id = 1141, Name = "SAN JOSÉ DE MIRANDA"},
                new Cities { Id = 1142, Name = "SAN MIGUEL"},
                new Cities { Id = 1143, Name = "SAN VICENTE DE CHUCURÍ"},
                new Cities { Id = 1144, Name = "SANTA BÁRBARA"},
                new Cities { Id = 1145, Name = "SANTA HELENA DEL OPÓN"},
                new Cities { Id = 1146, Name = "SIMACOTA"},
                new Cities { Id = 1147, Name = "SOCORRO"},
                new Cities { Id = 1148, Name = "SUAITA"},
                new Cities { Id = 1149, Name = "SUCRE"},
                new Cities { Id = 1150, Name = "SURATÁ"},
                new Cities { Id = 1151, Name = "TONA"},
                new Cities { Id = 1152, Name = "VALLE DE SAN JOSÉ"},
                new Cities { Id = 1153, Name = "VÉLEZ"},
                new Cities { Id = 1154, Name = "VETAS"},
                new Cities { Id = 1155, Name = "VILLANUEVA"},
                new Cities { Id = 1156, Name = "ZAPATOCA"},
                new Cities { Id = 1157, Name = "SINCELEJO"},
                new Cities { Id = 1158, Name = "BUENAVISTA"},
                new Cities { Id = 1159, Name = "CAIMITO"},
                new Cities { Id = 1160, Name = "COLOSO (RICAURTE)"},
                new Cities { Id = 1161, Name = "COROZAL"},
                new Cities { Id = 1162, Name = "CHALÁN"},
                new Cities { Id = 1163, Name = "GALERAS (NUEVA GRANADA)"},
                new Cities { Id = 1164, Name = "GUARANDÁ"},
                new Cities { Id = 1165, Name = "LA UNIÓN"},
                new Cities { Id = 1166, Name = "LOS PALMITOS"},
                new Cities { Id = 1167, Name = "MAJAGUAL"},
                new Cities { Id = 1168, Name = "MORROA"},
                new Cities { Id = 1169, Name = "OVEJAS"},
                new Cities { Id = 1170, Name = "PALMITO"},
                new Cities { Id = 1171, Name = "SAMPUÉS"},
                new Cities { Id = 1172, Name = "SAN BENITO ABAD"},
                new Cities { Id = 1173, Name = "SAN JUAN DE BETULIA"},
                new Cities { Id = 1174, Name = "SAN MARCOS"},
                new Cities { Id = 1175, Name = "SAN ONOFRE"},
                new Cities { Id = 1176, Name = "SAN PEDRO"},
                new Cities { Id = 1177, Name = "SINCÉ"},
                new Cities { Id = 1178, Name = "SUCRE"},
                new Cities { Id = 1179, Name = "TOLÚ"},
                new Cities { Id = 1180, Name = "TOLUVIEJO"},
                new Cities { Id = 1181, Name = "IBAGUÉ"},
                new Cities { Id = 1182, Name = "ALPUJARRA"},
                new Cities { Id = 1183, Name = "ALVARADO"},
                new Cities { Id = 1184, Name = "AMBALEMA"},
                new Cities { Id = 1185, Name = "ANZÓATEGUI"},
                new Cities { Id = 1186, Name = "ARMERO (GUAYABAL)"},
                new Cities { Id = 1187, Name = "ATACO"},
                new Cities { Id = 1188, Name = "CAJAMARCA"},
                new Cities { Id = 1189, Name = "CARMEN DE APICALÁ"},
                new Cities { Id = 1190, Name = "CASABIANCA"},
                new Cities { Id = 1191, Name = "CHAPARRAL"},
                new Cities { Id = 1192, Name = "COELLO"},
                new Cities { Id = 1193, Name = "COYAIMA"},
                new Cities { Id = 1194, Name = "CUNDAY"},
                new Cities { Id = 1195, Name = "DOLORES"},
                new Cities { Id = 1196, Name = "ESPINAL"},
                new Cities { Id = 1197, Name = "FALÁN"},
                new Cities { Id = 1198, Name = "FLANDES"},
                new Cities { Id = 1199, Name = "FRESNO"},
                new Cities { Id = 1200, Name = "GUAMO"},
                new Cities { Id = 1201, Name = "HERVEO"},
                new Cities { Id = 1202, Name = "HONDA"},
                new Cities { Id = 1203, Name = "ICONONZO"},
                new Cities { Id = 1204, Name = "LÉRIDA"},
                new Cities { Id = 1205, Name = "LÍBANO"},
                new Cities { Id = 1206, Name = "MARIQUITA"},
                new Cities { Id = 1207, Name = "MELGAR"},
                new Cities { Id = 1208, Name = "MURILLO"},
                new Cities { Id = 1209, Name = "NATAGAIMA"},
                new Cities { Id = 1210, Name = "ORTEGA"},
                new Cities { Id = 1211, Name = "PALOCABILDO"},
                new Cities { Id = 1212, Name = "PIEDRAS"},
                new Cities { Id = 1213, Name = "PLANADAS"},
                new Cities { Id = 1214, Name = "PRADO"},
                new Cities { Id = 1215, Name = "PURIFICACIÓN"},
                new Cities { Id = 1216, Name = "RIOBLANCO"},
                new Cities { Id = 1217, Name = "RONCESVALLES"},
                new Cities { Id = 1218, Name = "ROVIRA"},
                new Cities { Id = 1219, Name = "SALDAÑA"},
                new Cities { Id = 1220, Name = "SAN ANTONIO"},
                new Cities { Id = 1221, Name = "SAN LUIS"},
                new Cities { Id = 1222, Name = "SANTA ISABEL"},
                new Cities { Id = 1223, Name = "SUÁREZ"},
                new Cities { Id = 1224, Name = "VALLE DE SAN JUAN"},
                new Cities { Id = 1225, Name = "VENADILLO"},
                new Cities { Id = 1226, Name = "VILLAHERMOSA"},
                new Cities { Id = 1227, Name = "VILLARRICA"},
                new Cities { Id = 1228, Name = "CALI"},
                new Cities { Id = 1229, Name = "ALCALÁ"},
                new Cities { Id = 1230, Name = "ANDALUCÍA"},
                new Cities { Id = 1231, Name = "ANSERMANUEVO"},
                new Cities { Id = 1232, Name = "ARGELIA"},
                new Cities { Id = 1233, Name = "BOLÍVAR"},
                new Cities { Id = 1234, Name = "BUENAVENTURA"},
                new Cities { Id = 1235, Name = "BUGA"},
                new Cities { Id = 1236, Name = "BUGALAGRANDE"},
                new Cities { Id = 1237, Name = "CAICEDONIA"},
                new Cities { Id = 1238, Name = "CALIMA (DARIÉN)"},
                new Cities { Id = 1239, Name = "CANDELARIA"},
                new Cities { Id = 1240, Name = "CARTAGO"},
                new Cities { Id = 1241, Name = "DAGUA"},
                new Cities { Id = 1242, Name = "EL ÁGUILA"},
                new Cities { Id = 1243, Name = "EL CAIRO"},
                new Cities { Id = 1244, Name = "EL CERRITO"},
                new Cities { Id = 1245, Name = "EL DOVIO"},
                new Cities { Id = 1246, Name = "FLORIDA"},
                new Cities { Id = 1247, Name = "GINEBRA"},
                new Cities { Id = 1248, Name = "GUACARÍ"},
                new Cities { Id = 1249, Name = "JAMUNDÍ"},
                new Cities { Id = 1250, Name = "LA CUMBRE"},
                new Cities { Id = 1251, Name = "LA UNIÓN"},
                new Cities { Id = 1252, Name = "LA VICTORIA"},
                new Cities { Id = 1253, Name = "OBANDO"},
                new Cities { Id = 1254, Name = "PALMIRA"},
                new Cities { Id = 1255, Name = "PRADERA"},
                new Cities { Id = 1256, Name = "RESTREPO"},
                new Cities { Id = 1257, Name = "RIOFRÍO"},
                new Cities { Id = 1258, Name = "ROLDANILLO"},
                new Cities { Id = 1259, Name = "SAN PEDRO"},
                new Cities { Id = 1260, Name = "SEVILLA"},
                new Cities { Id = 1261, Name = "TORO"},
                new Cities { Id = 1262, Name = "TRUJILLO"},
                new Cities { Id = 1263, Name = "TULUÁ"},
                new Cities { Id = 1264, Name = "ULLOA"},
                new Cities { Id = 1265, Name = "VERSALLES"},
                new Cities { Id = 1266, Name = "VIJES"},
                new Cities { Id = 1267, Name = "YOTOCO"},
                new Cities { Id = 1268, Name = "YUMBO"},
                new Cities { Id = 1269, Name = "ZARZAL"},
                new Cities { Id = 1270, Name = "MITÚ"},
                new Cities { Id = 1271, Name = "CARURÚ"},
                new Cities { Id = 1272, Name = "TATAMÁ"},
                new Cities { Id = 1273, Name = "PUERTO CARREÑO"},
                new Cities { Id = 1274, Name = "LA PRIMAVERA"},
                new Cities { Id = 1275, Name = "SANTA ROSALIA"},
                new Cities { Id = 1276, Name = "CUMARIBO"}
            };

            return seeds;
        }
    }
}
